name: psicotuiterbot

on:
  push:
    branches: [main, master]
    tags: ['*']
  schedule:
    - cron: '*/5 * * * *'

jobs:
  psicotuiterbot-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 2
      - name: Install rtweet package
      - name: Create and post tweet
        run: Rscript bot.R
