name: psicotuiterbot

on:
  schedule:
    - cron: "* * * * *"

jobs:
  psicotuiterbot-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Update Linux libs
        run: sudo apt update && sudo apt upgrade
      - name: Install curl
        run: sudo apt install libcurl4-openssl-dev
      - name: Set up GitHub actions
        uses: actions/checkout@master
      - name: Set up R
        uses: r-lib/actions/setup-r@master
      - name: Set up setup renv
        uses: r-lib/actions/setup-renv@v1
      - name: Create and post tweet
        run: Rscript bot.R
