name: psicotuiterbot

on:
  schedule:
    - cron: '*/15 * * * *' # run every 15th minute
  push:
    branches:
      - main # run every time there is a push to main branch

jobs:

  psicotuiterbot-post:
    runs-on: ubuntu-latest
    env: #  twitter API keys (used to authenticate) defined in the gh actions environment
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      
    steps:
      - name: Install curl
        run: sudo apt install libcurl4-openssl-dev # rtweet system dependency
        
      - name: Set up GitHub actions
        uses: actions/checkout@v2
        with: # cache gh-actions
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3' # cache R version
          
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 2
            
      - name: Restore packages using renv
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Create and post tweet
        run: Rscript bot.R
